<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quiz;

class QuizSeeder extends Seeder
{
    public function run(): void
    {
        // Kosongkan dulu agar tidak dobel
        Quiz::truncate();

        $data = [
            [
                'kategori' => 'Geospasial & BIG',
                'pertanyaan' => 'Apa kepanjangan dari BIG dalam konteks geospasial Indonesia?',
                'a' => 'Badan Informasi Geospasial',
                'b' => 'Biro Informasi Geografi',
                'c' => 'Badan Ilmu Geologi',
                'd' => 'Balai Informasi Global',
                'jawaban' => 'a',
                'pembahasan' => 'BIG adalah Badan Informasi Geospasial, lembaga yang mengelola informasi geospasial nasional.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Dasar Geospasial',
                'pertanyaan' => 'Informasi geospasial umumnya menjawab pertanyaan utama berikut, kecuali…',
                'a' => 'Di mana lokasi suatu objek?',
                'b' => 'Bagaimana kondisi wilayah?',
                'c' => 'Berapa nilai saham perusahaan?',
                'd' => 'Apa yang ada di lokasi itu?',
                'jawaban' => 'c',
                'pembahasan' => 'Geospasial fokus pada lokasi dan kondisi wilayah, bukan finansial.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Peta',
                'pertanyaan' => 'Peta adalah…',
                'a' => 'Gambar bebas tanpa ukuran',
                'b' => 'Representasi permukaan bumi pada bidang datar',
                'c' => 'Daftar nama kota',
                'd' => 'Foto udara tanpa keterangan',
                'jawaban' => 'b',
                'pembahasan' => 'Peta merepresentasikan permukaan bumi pada bidang datar dengan skala dan simbol.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Kartografi',
                'pertanyaan' => 'Skala peta menunjukkan…',
                'a' => 'Warna peta',
                'b' => 'Perbandingan jarak pada peta dengan jarak sebenarnya',
                'c' => 'Nama tempat',
                'd' => 'Arah mata angin',
                'jawaban' => 'b',
                'pembahasan' => 'Skala = perbandingan jarak peta dan jarak di lapangan.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Kartografi',
                'pertanyaan' => 'Legenda pada peta berfungsi untuk…',
                'a' => 'Menentukan arah utara',
                'b' => 'Menjelaskan arti simbol pada peta',
                'c' => 'Mengukur jarak di peta',
                'd' => 'Menentukan koordinat',
                'jawaban' => 'b',
                'pembahasan' => 'Legenda menjelaskan simbol-simbol yang digunakan pada peta.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Koordinat',
                'pertanyaan' => 'Koordinat geografis terdiri dari…',
                'a' => 'Panjang dan lebar',
                'b' => 'Lintang dan bujur',
                'c' => 'Utara dan selatan',
                'd' => 'Timur dan barat',
                'jawaban' => 'b',
                'pembahasan' => 'Koordinat geografis menggunakan lintang (latitude) dan bujur (longitude).',
                'is_active' => true,
            ],
            [
                'kategori' => 'SIG',
                'pertanyaan' => 'SIG adalah singkatan dari…',
                'a' => 'Sistem Ilmu Geologi',
                'b' => 'Sistem Informasi Geografis',
                'c' => 'Sistem Integrasi Global',
                'd' => 'Satuan Informasi Geografi',
                'jawaban' => 'b',
                'pembahasan' => 'SIG (GIS) membantu mengelola, menganalisis, dan menampilkan data spasial.',
                'is_active' => true,
            ],
            [
                'kategori' => 'SIG',
                'pertanyaan' => 'Dalam SIG, data biasanya disusun dalam bentuk…',
                'a' => 'Layer (lapisan)',
                'b' => 'Cerita pendek',
                'c' => 'Musik',
                'd' => 'Video tanpa lokasi',
                'jawaban' => 'a',
                'pembahasan' => 'Layer memudahkan menumpuk beberapa jenis data (jalan, sungai, batas wilayah).',
                'is_active' => true,
            ],
            [
                'kategori' => 'Geodata',
                'pertanyaan' => 'Data spasial adalah data yang…',
                'a' => 'Berisi lokasi/koordinat',
                'b' => 'Hanya berisi angka keuangan',
                'c' => 'Tidak punya hubungan dengan lokasi',
                'd' => 'Hanya berisi teks narasi',
                'jawaban' => 'a',
                'pembahasan' => 'Data spasial punya referensi lokasi (geometri).',
                'is_active' => true,
            ],
            [
                'kategori' => 'Geodata',
                'pertanyaan' => 'Contoh data non-spasial (atribut) adalah…',
                'a' => 'Koordinat titik',
                'b' => 'Bentuk poligon wilayah',
                'c' => 'Nama kecamatan dan jumlah penduduk',
                'd' => 'Garis jalan pada peta',
                'jawaban' => 'c',
                'pembahasan' => 'Atribut seperti nama dan jumlah penduduk adalah data non-spasial.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Penerapan',
                'pertanyaan' => 'Peta rawan bencana digunakan untuk…',
                'a' => 'Memperindah buku',
                'b' => 'Membantu mitigasi dan perencanaan evakuasi',
                'c' => 'Menentukan harga barang',
                'd' => 'Mengukur tinggi badan',
                'jawaban' => 'b',
                'pembahasan' => 'Peta rawan bencana membantu mitigasi risiko dan rencana evakuasi.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Penerapan',
                'pertanyaan' => 'Pemanfaatan geospasial dalam tata ruang bertujuan untuk…',
                'a' => 'Menghindari konflik penggunaan lahan',
                'b' => 'Menambah spam iklan',
                'c' => 'Menghapus data peta',
                'd' => 'Membuat berita viral',
                'jawaban' => 'a',
                'pembahasan' => 'Data spasial membantu perencanaan wilayah sesuai zonasi.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Kartografi',
                'pertanyaan' => 'Arah mata angin pada peta membantu pengguna untuk…',
                'a' => 'Menentukan warna peta',
                'b' => 'Mengetahui orientasi (utara, selatan, timur, barat)',
                'c' => 'Mengubah ukuran peta',
                'd' => 'Membaca legenda',
                'jawaban' => 'b',
                'pembahasan' => 'Orientasi membantu memahami arah lokasi di peta.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Teknologi',
                'pertanyaan' => 'Citra satelit bermanfaat untuk…',
                'a' => 'Merekam perubahan permukaan bumi dari waktu ke waktu',
                'b' => 'Menghapus data peta',
                'c' => 'Mengukur suhu tubuh manusia',
                'd' => 'Membuat musik',
                'jawaban' => 'a',
                'pembahasan' => 'Citra satelit digunakan memantau perubahan lahan, hutan, urbanisasi, dll.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Kartografi',
                'pertanyaan' => 'Simbol pada peta digunakan untuk…',
                'a' => 'Mengganti teks',
                'b' => 'Merepresentasikan objek di permukaan bumi',
                'c' => 'Menentukan nilai ujian',
                'd' => 'Membuat peta menjadi berat',
                'jawaban' => 'b',
                'pembahasan' => 'Simbol memudahkan pembaca memahami objek (jalan, sungai, fasilitas).',
                'is_active' => true,
            ],
            [
                'kategori' => 'Peta',
                'pertanyaan' => 'Peta tematik adalah peta yang…',
                'a' => 'Menampilkan tema tertentu seperti kepadatan penduduk',
                'b' => 'Hanya berisi sungai dan jalan',
                'c' => 'Tidak memiliki legenda',
                'd' => 'Tidak memiliki skala',
                'jawaban' => 'a',
                'pembahasan' => 'Peta tematik fokus pada tema tertentu (bencana, demografi, lahan).',
                'is_active' => true,
            ],
            [
                'kategori' => 'Koordinat',
                'pertanyaan' => 'Jika lintang bernilai negatif, berarti lokasi berada di…',
                'a' => 'Belahan bumi utara',
                'b' => 'Belahan bumi selatan',
                'c' => 'Belahan bumi timur',
                'd' => 'Belahan bumi barat',
                'jawaban' => 'b',
                'pembahasan' => 'Lintang negatif menunjukkan posisi di belahan selatan.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Koordinat',
                'pertanyaan' => 'Jika bujur bernilai positif (umum), berarti lokasi berada di…',
                'a' => 'Belahan bumi barat',
                'b' => 'Belahan bumi timur',
                'c' => 'Belahan bumi utara',
                'd' => 'Belahan bumi selatan',
                'jawaban' => 'b',
                'pembahasan' => 'Bujur timur biasanya bernilai positif (konvensi umum).',
                'is_active' => true,
            ],
            [
                'kategori' => 'SIG',
                'pertanyaan' => 'Analisis jarak terdekat antara rumah dan rumah sakit dalam SIG termasuk…',
                'a' => 'Analisis spasial',
                'b' => 'Analisis musik',
                'c' => 'Analisis ekonomi',
                'd' => 'Analisis warna',
                'jawaban' => 'a',
                'pembahasan' => 'SIG melakukan analisis spasial seperti jarak, area, dan keterjangkauan.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Kebijakan',
                'pertanyaan' => 'Kebijakan “Satu Peta” (One Map Policy) bertujuan untuk…',
                'a' => 'Membuat banyak peta berbeda',
                'b' => 'Menyatukan referensi peta agar konsisten',
                'c' => 'Menghilangkan peta dasar',
                'd' => 'Membatasi data spasial',
                'jawaban' => 'b',
                'pembahasan' => 'One Map Policy mendorong satu referensi peta yang konsisten antar instansi.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Geodata',
                'pertanyaan' => 'Batas administrasi provinsi biasanya direpresentasikan sebagai…',
                'a' => 'Titik (point)',
                'b' => 'Garis (line)',
                'c' => 'Poligon (area)',
                'd' => 'Teks saja',
                'jawaban' => 'c',
                'pembahasan' => 'Wilayah administrasi adalah area, cocok sebagai poligon.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Geodata',
                'pertanyaan' => 'Jalan raya pada peta biasanya direpresentasikan sebagai…',
                'a' => 'Titik',
                'b' => 'Garis',
                'c' => 'Poligon',
                'd' => 'Tidak digambar',
                'jawaban' => 'b',
                'pembahasan' => 'Jalan adalah fitur linear, direpresentasikan sebagai garis.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Geodata',
                'pertanyaan' => 'Lokasi rumah sakit pada peta biasanya direpresentasikan sebagai…',
                'a' => 'Poligon besar',
                'b' => 'Garis',
                'c' => 'Titik',
                'd' => 'Tidak perlu ditampilkan',
                'jawaban' => 'c',
                'pembahasan' => 'Lokasi fasilitas sering ditandai sebagai titik.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Teknologi',
                'pertanyaan' => 'GPS digunakan untuk…',
                'a' => 'Menentukan posisi di permukaan bumi',
                'b' => 'Membuat peta menjadi berwarna',
                'c' => 'Menyimpan video',
                'd' => 'Menentukan suhu udara',
                'jawaban' => 'a',
                'pembahasan' => 'GPS membantu menentukan lokasi berbasis satelit.',
                'is_active' => true,
            ],
            [
                'kategori' => 'Penerapan',
                'pertanyaan' => 'Contoh penerapan data geospasial di bidang pertanian adalah…',
                'a' => 'Pemetaan lahan dan irigasi',
                'b' => 'Membuat musik tradisional',
                'c' => 'Menggambar bebas',
                'd' => 'Menyusun novel',
                'jawaban' => 'a',
                'pembahasan' => 'Geospasial digunakan untuk pemetaan lahan, irigasi, dan perencanaan tanam.',
                'is_active' => true,
            ],
        ];

        foreach ($data as $row) {
            Quiz::create($row);
        }
    }
}
